name: Backport PR by cherry-pick-ing
author: Nathan Malnoury
description: Automatically backport a PR onto another branch, based on cherry-pick-ing.
inputs:
  pr_branch:
    description: Branch to open new PR on.
    required: true
  github_token:
    description: Token for the GitHub API.
    required: true
branding:
  icon: chevron-left
  color: gray-dark
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.pr_branch }}
    - ${{ inputs.github_token }}
    - ${{ inputs.last_git_commit_message }}
